IF EXISTS(SELECT name FROM sys.tables WHERE name = 'ORDEN_TABLAS_CARGAR')
	DROP TABLE ORDEN_TABLAS_CARGAR
GO

CREATE TABLE ORDEN_TABLAS_CARGAR
(
	ID				INT PRIMARY KEY IDENTITY (1,1),
	NOMBRE_TABLA	VARCHAR(1000),
	ORDEN_TABLA		INT
)
GO

INSERT INTO ORDEN_TABLAS_CARGAR (NOMBRE_TABLA, ORDEN_TABLA) VALUES ('EstadoSolicitud', 1)
INSERT INTO ORDEN_TABLAS_CARGAR (NOMBRE_TABLA, ORDEN_TABLA) VALUES ('TipoSolicitud', 2)
INSERT INTO ORDEN_TABLAS_CARGAR (NOMBRE_TABLA, ORDEN_TABLA) VALUES ('TipoEmision', 3)
INSERT INTO ORDEN_TABLAS_CARGAR (NOMBRE_TABLA, ORDEN_TABLA) VALUES ('Solicitud', 4)
INSERT INTO ORDEN_TABLAS_CARGAR (NOMBRE_TABLA, ORDEN_TABLA) VALUES ('EstadoFactura', 5)
INSERT INTO ORDEN_TABLAS_CARGAR (NOMBRE_TABLA, ORDEN_TABLA) VALUES ('EstatusCancelacion', 6)
INSERT INTO ORDEN_TABLAS_CARGAR (NOMBRE_TABLA, ORDEN_TABLA) VALUES ('Comprobante', 7)

INSERT INTO ORDEN_TABLAS_CARGAR (NOMBRE_TABLA, ORDEN_TABLA) VALUES ('ImpuestosNodo0', 8)
INSERT INTO ORDEN_TABLAS_CARGAR (NOMBRE_TABLA, ORDEN_TABLA) VALUES ('RetencionesNodo0', 9)
INSERT INTO ORDEN_TABLAS_CARGAR (NOMBRE_TABLA, ORDEN_TABLA) VALUES ('RetencionNodo0', 10)
INSERT INTO ORDEN_TABLAS_CARGAR (NOMBRE_TABLA, ORDEN_TABLA) VALUES ('TrasladosNodo0', 11)
INSERT INTO ORDEN_TABLAS_CARGAR (NOMBRE_TABLA, ORDEN_TABLA) VALUES ('TrasladoNodo0', 12)

INSERT INTO ORDEN_TABLAS_CARGAR (NOMBRE_TABLA, ORDEN_TABLA) VALUES ('Receptor', 13)
INSERT INTO ORDEN_TABLAS_CARGAR (NOMBRE_TABLA, ORDEN_TABLA) VALUES ('Emisor', 14)
INSERT INTO ORDEN_TABLAS_CARGAR (NOMBRE_TABLA, ORDEN_TABLA) VALUES ('CfdiRelacionados', 15)
INSERT INTO ORDEN_TABLAS_CARGAR (NOMBRE_TABLA, ORDEN_TABLA) VALUES ('CfdiRelacionado', 16)

INSERT INTO ORDEN_TABLAS_CARGAR (NOMBRE_TABLA, ORDEN_TABLA) VALUES ('Addenda', 17)
INSERT INTO ORDEN_TABLAS_CARGAR (NOMBRE_TABLA, ORDEN_TABLA) VALUES ('Conceptos', 18)
INSERT INTO ORDEN_TABLAS_CARGAR (NOMBRE_TABLA, ORDEN_TABLA) VALUES ('Concepto', 19)

INSERT INTO ORDEN_TABLAS_CARGAR (NOMBRE_TABLA, ORDEN_TABLA) VALUES ('Impuestos', 20)
INSERT INTO ORDEN_TABLAS_CARGAR (NOMBRE_TABLA, ORDEN_TABLA) VALUES ('Retenciones', 21)
INSERT INTO ORDEN_TABLAS_CARGAR (NOMBRE_TABLA, ORDEN_TABLA) VALUES ('Retencion', 22)
INSERT INTO ORDEN_TABLAS_CARGAR (NOMBRE_TABLA, ORDEN_TABLA) VALUES ('Traslados', 23)
INSERT INTO ORDEN_TABLAS_CARGAR (NOMBRE_TABLA, ORDEN_TABLA) VALUES ('Traslado', 24)

INSERT INTO ORDEN_TABLAS_CARGAR (NOMBRE_TABLA, ORDEN_TABLA) VALUES ('CuentaPredial', 25)
INSERT INTO ORDEN_TABLAS_CARGAR (NOMBRE_TABLA, ORDEN_TABLA) VALUES ('ComplementoConcepto', 26)
INSERT INTO ORDEN_TABLAS_CARGAR (NOMBRE_TABLA, ORDEN_TABLA) VALUES ('Parte', 27)
INSERT INTO ORDEN_TABLAS_CARGAR (NOMBRE_TABLA, ORDEN_TABLA) VALUES ('InformacionAduanera', 28)

INSERT INTO ORDEN_TABLAS_CARGAR (NOMBRE_TABLA, ORDEN_TABLA) VALUES ('Complemento', 29)
INSERT INTO ORDEN_TABLAS_CARGAR (NOMBRE_TABLA, ORDEN_TABLA) VALUES ('TimbreFiscalDigital', 30)
INSERT INTO ORDEN_TABLAS_CARGAR (NOMBRE_TABLA, ORDEN_TABLA) VALUES ('Pagos', 31)
INSERT INTO ORDEN_TABLAS_CARGAR (NOMBRE_TABLA, ORDEN_TABLA) VALUES ('Pago', 32)
INSERT INTO ORDEN_TABLAS_CARGAR (NOMBRE_TABLA, ORDEN_TABLA) VALUES ('DoctoRelacionado', 33)

INSERT INTO ORDEN_TABLAS_CARGAR (NOMBRE_TABLA, ORDEN_TABLA) VALUES ('Nomina', 34)
INSERT INTO ORDEN_TABLAS_CARGAR (NOMBRE_TABLA, ORDEN_TABLA) VALUES ('Incapacidades', 35)
INSERT INTO ORDEN_TABLAS_CARGAR (NOMBRE_TABLA, ORDEN_TABLA) VALUES ('Incapacidad', 36)
INSERT INTO ORDEN_TABLAS_CARGAR (NOMBRE_TABLA, ORDEN_TABLA) VALUES ('Deducciones', 37)
INSERT INTO ORDEN_TABLAS_CARGAR (NOMBRE_TABLA, ORDEN_TABLA) VALUES ('Deduccion', 38)

INSERT INTO ORDEN_TABLAS_CARGAR (NOMBRE_TABLA, ORDEN_TABLA) VALUES ('EmisorNomina', 39)
INSERT INTO ORDEN_TABLAS_CARGAR (NOMBRE_TABLA, ORDEN_TABLA) VALUES ('EntidadSNCF', 40)

INSERT INTO ORDEN_TABLAS_CARGAR (NOMBRE_TABLA, ORDEN_TABLA) VALUES ('OtrosPagos', 41)
INSERT INTO ORDEN_TABLAS_CARGAR (NOMBRE_TABLA, ORDEN_TABLA) VALUES ('OtroPago', 42)
INSERT INTO ORDEN_TABLAS_CARGAR (NOMBRE_TABLA, ORDEN_TABLA) VALUES ('SubsidioAlEmpleo', 43)
INSERT INTO ORDEN_TABLAS_CARGAR (NOMBRE_TABLA, ORDEN_TABLA) VALUES ('CompensacionSaldosAFavor', 44)

INSERT INTO ORDEN_TABLAS_CARGAR (NOMBRE_TABLA, ORDEN_TABLA) VALUES ('ReceptorNomina', 45)
INSERT INTO ORDEN_TABLAS_CARGAR (NOMBRE_TABLA, ORDEN_TABLA) VALUES ('SubContratacion', 46)

INSERT INTO ORDEN_TABLAS_CARGAR (NOMBRE_TABLA, ORDEN_TABLA) VALUES ('Percepciones', 47)
INSERT INTO ORDEN_TABLAS_CARGAR (NOMBRE_TABLA, ORDEN_TABLA) VALUES ('SeparacionIndemnizacion', 48)
INSERT INTO ORDEN_TABLAS_CARGAR (NOMBRE_TABLA, ORDEN_TABLA) VALUES ('JubilacionPensionRetiro', 49)

INSERT INTO ORDEN_TABLAS_CARGAR (NOMBRE_TABLA, ORDEN_TABLA) VALUES ('Percepcion', 50)
INSERT INTO ORDEN_TABLAS_CARGAR (NOMBRE_TABLA, ORDEN_TABLA) VALUES ('HorasExtra', 51)
INSERT INTO ORDEN_TABLAS_CARGAR (NOMBRE_TABLA, ORDEN_TABLA) VALUES ('AccionesOTitulos', 52)

INSERT INTO ORDEN_TABLAS_CARGAR (NOMBRE_TABLA, ORDEN_TABLA) VALUES ('MetadataSAT', 53)
INSERT INTO ORDEN_TABLAS_CARGAR (NOMBRE_TABLA, ORDEN_TABLA) VALUES ('PersonaFisicaMoral', 54)





SELECT ID, NOMBRE_TABLA, ORDEN_TABLA FROM ORDEN_TABLAS_CARGAR ORDER BY ORDEN_TABLA


SELECT 'INSERT INTO @Table1 SELECT '''+NOMBRE_TABLA+''', COUNT(*) FROM '+NOMBRE_TABLA  FROM ORDEN_TABLAS_CARGAR ORDER BY ORDEN_TABLA

DECLARE @Table1 TABLE (NOMBRE  VARCHAR(200), NUMERO  INT)
INSERT INTO @Table1 SELECT 'EstadoSolicitud', COUNT(*) FROM EstadoSolicitud
INSERT INTO @Table1 SELECT 'TipoSolicitud', COUNT(*) FROM TipoSolicitud
INSERT INTO @Table1 SELECT 'TipoEmision', COUNT(*) FROM TipoEmision
INSERT INTO @Table1 SELECT 'Solicitud', COUNT(*) FROM Solicitud
INSERT INTO @Table1 SELECT 'EstadoFactura', COUNT(*) FROM EstadoFactura
INSERT INTO @Table1 SELECT 'EstatusCancelacion', COUNT(*) FROM EstatusCancelacion
INSERT INTO @Table1 SELECT 'Comprobante', COUNT(*) FROM Comprobante
INSERT INTO @Table1 SELECT 'ImpuestosNodo0', COUNT(*) FROM ImpuestosNodo0
INSERT INTO @Table1 SELECT 'RetencionesNodo0', COUNT(*) FROM RetencionesNodo0
INSERT INTO @Table1 SELECT 'RetencionNodo0', COUNT(*) FROM RetencionNodo0
INSERT INTO @Table1 SELECT 'TrasladosNodo0', COUNT(*) FROM TrasladosNodo0
INSERT INTO @Table1 SELECT 'TrasladoNodo0', COUNT(*) FROM TrasladoNodo0
INSERT INTO @Table1 SELECT 'Receptor', COUNT(*) FROM Receptor
INSERT INTO @Table1 SELECT 'Emisor', COUNT(*) FROM Emisor
INSERT INTO @Table1 SELECT 'CfdiRelacionados', COUNT(*) FROM CfdiRelacionados
INSERT INTO @Table1 SELECT 'CfdiRelacionado', COUNT(*) FROM CfdiRelacionado
INSERT INTO @Table1 SELECT 'Addenda', COUNT(*) FROM Addenda
INSERT INTO @Table1 SELECT 'Conceptos', COUNT(*) FROM Conceptos
INSERT INTO @Table1 SELECT 'Concepto', COUNT(*) FROM Concepto
INSERT INTO @Table1 SELECT 'Impuestos', COUNT(*) FROM Impuestos
INSERT INTO @Table1 SELECT 'Retenciones', COUNT(*) FROM Retenciones
INSERT INTO @Table1 SELECT 'Retencion', COUNT(*) FROM Retencion
INSERT INTO @Table1 SELECT 'Traslados', COUNT(*) FROM Traslados
INSERT INTO @Table1 SELECT 'Traslado', COUNT(*) FROM Traslado
INSERT INTO @Table1 SELECT 'CuentaPredial', COUNT(*) FROM CuentaPredial
INSERT INTO @Table1 SELECT 'ComplementoConcepto', COUNT(*) FROM ComplementoConcepto
INSERT INTO @Table1 SELECT 'Parte', COUNT(*) FROM Parte
INSERT INTO @Table1 SELECT 'InformacionAduanera', COUNT(*) FROM InformacionAduanera
INSERT INTO @Table1 SELECT 'Complemento', COUNT(*) FROM Complemento
INSERT INTO @Table1 SELECT 'TimbreFiscalDigital', COUNT(*) FROM TimbreFiscalDigital
INSERT INTO @Table1 SELECT 'Pagos', COUNT(*) FROM Pagos
INSERT INTO @Table1 SELECT 'Pago', COUNT(*) FROM Pago
INSERT INTO @Table1 SELECT 'DoctoRelacionado', COUNT(*) FROM DoctoRelacionado
INSERT INTO @Table1 SELECT 'Nomina', COUNT(*) FROM Nomina
INSERT INTO @Table1 SELECT 'Incapacidades', COUNT(*) FROM Incapacidades
INSERT INTO @Table1 SELECT 'Incapacidad', COUNT(*) FROM Incapacidad
INSERT INTO @Table1 SELECT 'Deducciones', COUNT(*) FROM Deducciones
INSERT INTO @Table1 SELECT 'Deduccion', COUNT(*) FROM Deduccion
INSERT INTO @Table1 SELECT 'EmisorNomina', COUNT(*) FROM EmisorNomina
INSERT INTO @Table1 SELECT 'EntidadSNCF', COUNT(*) FROM EntidadSNCF
INSERT INTO @Table1 SELECT 'OtrosPagos', COUNT(*) FROM OtrosPagos
INSERT INTO @Table1 SELECT 'OtroPago', COUNT(*) FROM OtroPago
INSERT INTO @Table1 SELECT 'SubsidioAlEmpleo', COUNT(*) FROM SubsidioAlEmpleo
INSERT INTO @Table1 SELECT 'CompensacionSaldosAFavor', COUNT(*) FROM CompensacionSaldosAFavor
INSERT INTO @Table1 SELECT 'ReceptorNomina', COUNT(*) FROM ReceptorNomina
INSERT INTO @Table1 SELECT 'SubContratacion', COUNT(*) FROM SubContratacion
INSERT INTO @Table1 SELECT 'Percepciones', COUNT(*) FROM Percepciones
INSERT INTO @Table1 SELECT 'SeparacionIndemnizacion', COUNT(*) FROM SeparacionIndemnizacion
INSERT INTO @Table1 SELECT 'JubilacionPensionRetiro', COUNT(*) FROM JubilacionPensionRetiro
INSERT INTO @Table1 SELECT 'Percepcion', COUNT(*) FROM Percepcion
INSERT INTO @Table1 SELECT 'HorasExtra', COUNT(*) FROM HorasExtra
INSERT INTO @Table1 SELECT 'AccionesOTitulos', COUNT(*) FROM AccionesOTitulos
INSERT INTO @Table1 SELECT 'MetadataSAT', COUNT(*) FROM MetadataSAT
INSERT INTO @Table1 SELECT 'PersonaFisicaMoral', COUNT(*) FROM PersonaFisicaMoral

SELECT * FROM @Table1







